# resources:
resources:
   - name: kubeClusterIntegrationResource
     type: KubeCluster
     configuration:
       kubernetesConfig: ranjan
       bastionHostIP: 1.2.3.4  # optional
#        bastionUser: sshUser  # optional
#        bastionIntegrationName: sshKeyIntegration  # optional
#   - name: simple_test
#     type: GitRepo
#     configuration:
#       gitProvider: ranjan_github
#       path: Ranjansingh41/test 
      
pipelines:
  - name: pipeline_ranjan
    steps:
      - name: node
        type: Bash
        configuration:
          nodePool: on-demand-nodes
          inputResources:
            - name: kubeClusterIntegrationResource
          runtime:
            type: image
            image:
              custom:
                name: ankul/u16
                tag: master
        execution:
          onExecute:
            - printenv
